# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kobus/Kobus/clion_workspace/Nedi-image-upscaling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kobus/Kobus/clion_workspace/Nedi-image-upscaling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kobus/Kobus/clion_workspace/Nedi-image-upscaling/CMakeFiles /home/kobus/Kobus/clion_workspace/Nedi-image-upscaling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kobus/Kobus/clion_workspace/Nedi-image-upscaling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pipeline

# Build rule for target.
Pipeline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pipeline
.PHONY : Pipeline

# fast build rule for target.
Pipeline/fast:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/build
.PHONY : Pipeline/fast

src/gui/gui_thread.o: src/gui/gui_thread.cpp.o
.PHONY : src/gui/gui_thread.o

# target to build an object file
src/gui/gui_thread.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/gui_thread.cpp.o
.PHONY : src/gui/gui_thread.cpp.o

src/gui/gui_thread.i: src/gui/gui_thread.cpp.i
.PHONY : src/gui/gui_thread.i

# target to preprocess a source file
src/gui/gui_thread.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/gui_thread.cpp.i
.PHONY : src/gui/gui_thread.cpp.i

src/gui/gui_thread.s: src/gui/gui_thread.cpp.s
.PHONY : src/gui/gui_thread.s

# target to generate assembly for a file
src/gui/gui_thread.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/gui_thread.cpp.s
.PHONY : src/gui/gui_thread.cpp.s

src/gui/widgets.o: src/gui/widgets.cpp.o
.PHONY : src/gui/widgets.o

# target to build an object file
src/gui/widgets.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/widgets.cpp.o
.PHONY : src/gui/widgets.cpp.o

src/gui/widgets.i: src/gui/widgets.cpp.i
.PHONY : src/gui/widgets.i

# target to preprocess a source file
src/gui/widgets.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/widgets.cpp.i
.PHONY : src/gui/widgets.cpp.i

src/gui/widgets.s: src/gui/widgets.cpp.s
.PHONY : src/gui/widgets.s

# target to generate assembly for a file
src/gui/widgets.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/gui/widgets.cpp.s
.PHONY : src/gui/widgets.cpp.s

src/imageProcessing/cpuDsp.o: src/imageProcessing/cpuDsp.cpp.o
.PHONY : src/imageProcessing/cpuDsp.o

# target to build an object file
src/imageProcessing/cpuDsp.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/cpuDsp.cpp.o
.PHONY : src/imageProcessing/cpuDsp.cpp.o

src/imageProcessing/cpuDsp.i: src/imageProcessing/cpuDsp.cpp.i
.PHONY : src/imageProcessing/cpuDsp.i

# target to preprocess a source file
src/imageProcessing/cpuDsp.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/cpuDsp.cpp.i
.PHONY : src/imageProcessing/cpuDsp.cpp.i

src/imageProcessing/cpuDsp.s: src/imageProcessing/cpuDsp.cpp.s
.PHONY : src/imageProcessing/cpuDsp.s

# target to generate assembly for a file
src/imageProcessing/cpuDsp.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/cpuDsp.cpp.s
.PHONY : src/imageProcessing/cpuDsp.cpp.s

src/imageProcessing/imageStabKalman.o: src/imageProcessing/imageStabKalman.cpp.o
.PHONY : src/imageProcessing/imageStabKalman.o

# target to build an object file
src/imageProcessing/imageStabKalman.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/imageStabKalman.cpp.o
.PHONY : src/imageProcessing/imageStabKalman.cpp.o

src/imageProcessing/imageStabKalman.i: src/imageProcessing/imageStabKalman.cpp.i
.PHONY : src/imageProcessing/imageStabKalman.i

# target to preprocess a source file
src/imageProcessing/imageStabKalman.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/imageStabKalman.cpp.i
.PHONY : src/imageProcessing/imageStabKalman.cpp.i

src/imageProcessing/imageStabKalman.s: src/imageProcessing/imageStabKalman.cpp.s
.PHONY : src/imageProcessing/imageStabKalman.s

# target to generate assembly for a file
src/imageProcessing/imageStabKalman.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/imageStabKalman.cpp.s
.PHONY : src/imageProcessing/imageStabKalman.cpp.s

src/imageProcessing/stabilisation.o: src/imageProcessing/stabilisation.cpp.o
.PHONY : src/imageProcessing/stabilisation.o

# target to build an object file
src/imageProcessing/stabilisation.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/stabilisation.cpp.o
.PHONY : src/imageProcessing/stabilisation.cpp.o

src/imageProcessing/stabilisation.i: src/imageProcessing/stabilisation.cpp.i
.PHONY : src/imageProcessing/stabilisation.i

# target to preprocess a source file
src/imageProcessing/stabilisation.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/stabilisation.cpp.i
.PHONY : src/imageProcessing/stabilisation.cpp.i

src/imageProcessing/stabilisation.s: src/imageProcessing/stabilisation.cpp.s
.PHONY : src/imageProcessing/stabilisation.s

# target to generate assembly for a file
src/imageProcessing/stabilisation.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/imageProcessing/stabilisation.cpp.s
.PHONY : src/imageProcessing/stabilisation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ti/camera.o: src/ti/camera.cpp.o
.PHONY : src/ti/camera.o

# target to build an object file
src/ti/camera.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/camera.cpp.o
.PHONY : src/ti/camera.cpp.o

src/ti/camera.i: src/ti/camera.cpp.i
.PHONY : src/ti/camera.i

# target to preprocess a source file
src/ti/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/camera.cpp.i
.PHONY : src/ti/camera.cpp.i

src/ti/camera.s: src/ti/camera.cpp.s
.PHONY : src/ti/camera.s

# target to generate assembly for a file
src/ti/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/camera.cpp.s
.PHONY : src/ti/camera.cpp.s

src/ti/ti_thread.o: src/ti/ti_thread.cpp.o
.PHONY : src/ti/ti_thread.o

# target to build an object file
src/ti/ti_thread.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/ti_thread.cpp.o
.PHONY : src/ti/ti_thread.cpp.o

src/ti/ti_thread.i: src/ti/ti_thread.cpp.i
.PHONY : src/ti/ti_thread.i

# target to preprocess a source file
src/ti/ti_thread.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/ti_thread.cpp.i
.PHONY : src/ti/ti_thread.cpp.i

src/ti/ti_thread.s: src/ti/ti_thread.cpp.s
.PHONY : src/ti/ti_thread.s

# target to generate assembly for a file
src/ti/ti_thread.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/ti/ti_thread.cpp.s
.PHONY : src/ti/ti_thread.cpp.s

src/util/threads.o: src/util/threads.cpp.o
.PHONY : src/util/threads.o

# target to build an object file
src/util/threads.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/threads.cpp.o
.PHONY : src/util/threads.cpp.o

src/util/threads.i: src/util/threads.cpp.i
.PHONY : src/util/threads.i

# target to preprocess a source file
src/util/threads.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/threads.cpp.i
.PHONY : src/util/threads.cpp.i

src/util/threads.s: src/util/threads.cpp.s
.PHONY : src/util/threads.s

# target to generate assembly for a file
src/util/threads.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/threads.cpp.s
.PHONY : src/util/threads.cpp.s

src/util/timeClock.o: src/util/timeClock.cpp.o
.PHONY : src/util/timeClock.o

# target to build an object file
src/util/timeClock.cpp.o:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/timeClock.cpp.o
.PHONY : src/util/timeClock.cpp.o

src/util/timeClock.i: src/util/timeClock.cpp.i
.PHONY : src/util/timeClock.i

# target to preprocess a source file
src/util/timeClock.cpp.i:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/timeClock.cpp.i
.PHONY : src/util/timeClock.cpp.i

src/util/timeClock.s: src/util/timeClock.cpp.s
.PHONY : src/util/timeClock.s

# target to generate assembly for a file
src/util/timeClock.cpp.s:
	$(MAKE) -f CMakeFiles/Pipeline.dir/build.make CMakeFiles/Pipeline.dir/src/util/timeClock.cpp.s
.PHONY : src/util/timeClock.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pipeline"
	@echo "... src/gui/gui_thread.o"
	@echo "... src/gui/gui_thread.i"
	@echo "... src/gui/gui_thread.s"
	@echo "... src/gui/widgets.o"
	@echo "... src/gui/widgets.i"
	@echo "... src/gui/widgets.s"
	@echo "... src/imageProcessing/cpuDsp.o"
	@echo "... src/imageProcessing/cpuDsp.i"
	@echo "... src/imageProcessing/cpuDsp.s"
	@echo "... src/imageProcessing/imageStabKalman.o"
	@echo "... src/imageProcessing/imageStabKalman.i"
	@echo "... src/imageProcessing/imageStabKalman.s"
	@echo "... src/imageProcessing/stabilisation.o"
	@echo "... src/imageProcessing/stabilisation.i"
	@echo "... src/imageProcessing/stabilisation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ti/camera.o"
	@echo "... src/ti/camera.i"
	@echo "... src/ti/camera.s"
	@echo "... src/ti/ti_thread.o"
	@echo "... src/ti/ti_thread.i"
	@echo "... src/ti/ti_thread.s"
	@echo "... src/util/threads.o"
	@echo "... src/util/threads.i"
	@echo "... src/util/threads.s"
	@echo "... src/util/timeClock.o"
	@echo "... src/util/timeClock.i"
	@echo "... src/util/timeClock.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

